baseURL = "https://jimzenn.com/"
languageCode = "en-us"
title = "Jim Zenn"
author = "Jim Zenn"
theme = "zealoft"
preserveTaxonomyNames = true
googleAnalytics = "UA-83942334-3"

[params]
  my_name = "Jim Zenn"
  my_education = "University of California, Los Angeles"
  email = "zenn@ucla.edu"
  my_major = "Applied Mathematics"
  github = "https://github.com/Jim-Zenn"
  CV = "/CV.pdf"
  version = "2.9.3"

# [menu]
#   [[menu.main]]
#     identifier = "math-115A"
#     name = "Math 115A"
#     url = "/math-115a/main/"
#     weight = 1

[taxonomies]
  category = "volumes"
  tag = "keywords"
